// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/14/2025, 1:26:57 PM
const configMerger = require("C:/Users/Sofia Joy D. Yunun/Downloads/ITS-SoftDev/its-web-softdev/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/Sofia Joy D. Yunun/Downloads/ITS-SoftDev/its-web-softdev/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Sofia Joy D. Yunun/Downloads/ITS-SoftDev/its-web-softdev/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Sofia Joy D. Yunun/Downloads/ITS-SoftDev/its-web-softdev/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Sofia Joy D. Yunun/Downloads/ITS-SoftDev/its-web-softdev/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Sofia Joy D. Yunun/Downloads/ITS-SoftDev/its-web-softdev/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Sofia Joy D. Yunun/Downloads/ITS-SoftDev/its-web-softdev/app/plugins/**/*.{js,ts,mjs}","C:/Users/Sofia Joy D. Yunun/Downloads/ITS-SoftDev/its-web-softdev/app/composables/**/*.{js,ts,mjs}","C:/Users/Sofia Joy D. Yunun/Downloads/ITS-SoftDev/its-web-softdev/app/utils/**/*.{js,ts,mjs}","C:/Users/Sofia Joy D. Yunun/Downloads/ITS-SoftDev/its-web-softdev/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Sofia Joy D. Yunun/Downloads/ITS-SoftDev/its-web-softdev/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Sofia Joy D. Yunun/Downloads/ITS-SoftDev/its-web-softdev/app/app.config.{js,ts,mjs}"] } }));

module.exports = config
